kernel32: dq ?
get_last_error: dq ?
get_proc_address: dq ?
load_library_a: dq ?
get_module_handle_a: dq ?
get_current_process: dq ?
get_volume_information_a: dq ?
get_volume_information_w: dq ?
get_std_handle: dq ?
open_process: dq ?
open_file: dq ?
get_file_size: dq ?
create_file_a: dq ?
create_file_w: dq ?
read_file: dq ?
set_file_pointer: dq ?
find_first_stream_w: dq ?
find_next_stream_w: dq ?
find_close: dq ?
write_file: dq ?
virtual_alloc: dq ?
virtual_alloc_ex: dq ?
virtual_protect: dq ?
virtual_protect_ex: dq ?
virtual_free: dq ?
virtual_free_ex: dq ?
read_process_memory: dq ?
write_process_memory: dq ?
create_remote_thread: dq ?
wait_for_single_object: dq ?
close_handle: dq ?
create_toolhelp32_snapshot: dq ?
process32_first: dq ?
process32_next: dq ?
sleep: dq ?
output_debug_string_a: dq ?