kernel32: dd ?
get_last_error: dd ?
get_proc_address: dd ?
load_library_a: dd ?
get_module_handle_a: dd ?
get_current_process: dd ?
get_std_handle: dd ?
open_process: dd ?
open_file: dd ?
get_file_size: dd ?
create_file_a: dd ?
read_file: dd ?
write_file: dd ?
virtual_alloc: dd ?
virtual_alloc_ex: dd ?
virtual_protect_ex: dd ?
virtual_protect: dd ?
virtual_free: dd ?
virtual_free_ex: dd ?
read_process_memory: dd ?
write_process_memory: dd ?
create_remote_thread: dd ?
wait_for_single_object: dd ?
close_handle: dd ?
create_toolhelp32_snapshot: dd ?
process32_first: dd ?
process32_next: dd ?
sleep: dd ?
resume_thread: dd ?
output_debug_string_a: dd ?